name: Docker Auto Update with Version Control

on:
  push:
    branches:
      - main

jobs:
  update-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Update version
        run: |
          # Read current version from version.txt
          CURRENT_VERSION=$(cat version.txt)
          # Increment the version
          NEW_VERSION=$((CURRENT_VERSION + 1))
          # Update the version in version.txt
          echo $NEW_VERSION > version.txt
          # Set output variable for later steps
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Build and push Docker image
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          NEW_VERSION: ${{ steps.update-version.outputs.new_version }}
        run: |
          # Log in to Docker Hub or your container registry
          echo A@shokak10299 | docker login  -u ashokxylo --password-stdin

          # Build and push the Docker image with the new version tag
          docker buildx build -t ashokxylo/kprui:$NEW_VERSION .

          # Push the updated image tag
          docker push ashokxylo/kprui:$NEW_VERSION
