name: Update Version and Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "VERSION_NUMBER=${{ secrets.VERSION_NUMBER }}" >> $GITHUB_ENV
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}" >> $GITHUB_ENV

      - name: Update Version Number
        run: |
          CURRENT_VERSION=$VERSION_NUMBER
          NEW_VERSION=$((CURRENT_VERSION + 1))
          echo $NEW_VERSION > version.txt
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ashokxylo
          password: A@shokak101299
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ashokxylo/tradeui:NEW_VERSION  

#      - name: Build and Push Docker Im#age
#          DOCKER_IMAGE_NAME=kprui
 #         DOCKER_USERNAME=$DOCKERHUB_USERNAME
  #        DOCKER_PASSWORD=$DOCKERHUB_PASSWORD
   #       NEW_VERSION=$NEW_VERSION
#
 #         docker build -t $DOCKER_IMAGE_NAME:$NEW_VERSION .
  #        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
   #       docker push $DOCKER_IMAGE_NAME:$NEW_VERSION 
