name: Update Version and Build Docker Image
on:
  push:
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine New Version
        id: version
        run: |
          # Your script to determine the new version
          # For example:
          echo "::set-output name=new_version::1.0.0"

      - name: Update Version File
        run: |
          # Update the version file with the new version
          # For example:
          echo "${{ steps.version.outputs.new_version }}" > version.txt
          git add version.txt
          git commit -m "Update version to ${{ steps.version.outputs.new_version }}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ashokxylo/kprui:${{ steps.version.outputs.new_version }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Changes
        run: git push
